server:
  port: 9092

spring:
  application:
    name: budget-servicef
  output:
    ansi:
      enabled: always
  threads:
    virtual:
      enabled: true
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:5527/${DB_NAME:budget-db}
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:postgres}
    hikari:
      connection-timeout: 20000
      idle-timeout: 600000
      max-lifetime: 1800000
      maximum-pool-size: 10
      minimum-idle: 5
      connection-test-query: SELECT 1
  flyway:
    enabled: true
    url: jdbc:postgresql://${DB_HOST:localhost}:5527/${DB_NAME:budget-db}
    user: postgres
    password: postgres
    baseline-on-migrate: true
    schemas: budget_service
    locations: classpath:db/migration
    default-schema: budget_service
  logging:
    level:
      root: INFO
management:
  endpoints:
    web:
      exposure:
        include: health, info, prometheus
  endpoint:
    prometheus:
      enabled: true
    metrics:
      export:
        prometheus:
          enabled: true
    health:
      show-details: always
